//Getting seacrh term
export const GET_SVALUE_REQUEST = "GET_SVALUE_REQUEST";
export const GET_SVALUE_SUCCESS = "GET_SVALUE_SUCCESS";
export const GET_SVALUE_FAILURE = "GET_SVALUE_FAILURE";

//Api calls to Google books
export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE";

//Call to DB
export const GET_SBOOKS_REQUEST = "GET_SBOOKS_REQUEST";
export const GET_SBOOKS_SUCCESS = "GET_SBOOKS_SUCCESS";
export const GET_SBOOKS_FAILURE = "GET_SBOOKS_FAILURE";

//save books
export const SAVE_BOOK_REQUEST = "SAVE_BOOK_REQUEST";
export const SAVE_BOOK_SUCCESS = "SAVE_BOOK_SUCCESS";
export const SAVE_BOOK_FAILURE = "SAVE_BOOK_FAILURE";